---
title: "Climate change"
author: "Alexander Wu, Andy Vu Hoang, and Vicky Hoang"
geometry: margin=0.75in
output: pdf_document
---


```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache=TRUE,
                      warning = FALSE)
# library(dplyr)
library(ggplot2)
library(plotly)
library(ggfortify) # to plot ts with ggplot2
library(pander) # nice formatting
library(stringr) # manipulating strings
library(lubridate) # working with date objects
library(MASS) # for stats stuff
library(tseries) # time series stuff
```

## Importing data

```{r}
fire <- read.csv("data/GlobalTemperatures.csv", header = TRUE, stringsAsFactors = FALSE)
fire$dt <- as.Date(fire$dt)
dim(fire)
```

## Making a time series with average land temperature
```{r}
temp <- fire$LandAverageTemperature
sum(is.na(temp))
which(is.na(temp))
# Selecting from January 1753 and on so that there's no NAs
temp.ts <- ts(temp[37:length(temp)], start=c(1753, 1), frequency=12)
time.plot <- autoplot(temp.ts, main="Monthly Average Temperature in Celsius", ts.colour="firebrick",
                      size=1)
ggplotly(time.plot)
# We have a bunch of points, plotting trend instead
trend.plot <- autoplot(decompose(temp.ts)$trend, main="Average Temperature Trend", ts.colour="goldenrod")
ggplotly(trend.plot)
```

## Making a time series from 1950 and on
```{r}
modern.ts <- ts(temp[2401:(length(temp)-12)], start=c(1950,1), freq=12) # excluding last 12 obs to later use to verify model
trend.mod <- decompose(modern.ts)$trend
colors <- c("firebrick", "yellow1")
autoplot(ts(cbind(modern.ts, trend.mod), start=c(1950, 1), freq=12), facets=FALSE, size=1) +
  scale_color_manual(values=colors)
autoplot(trend.mod, main="Average Temperature Trend in Celsius", ts.colour="yellow1", size=1.5)
```

## Time Series Analysis

#### Box Cox Transform
```{r}
# Currently, data is clearly not stationary since it trends upwards
# Testing to see if data needs transformation due to non-constant variance
bcTransform <- boxcox(modern.ts ~ as.numeric(1:length(modern.ts)))
lambda <- bcTransform$x[which(bcTransform$y==max(bcTransform$y))] # lambda=0.707070...
temp.tr <- (1/0.7)*(modern.ts^0.7-1)
```

#### Differencing
```{r}
# When variance goes up after differencing, I've differenced too much
var(temp.tr)
d.temp.tr <- diff(temp.tr, lag=1)
var(d.temp.tr)
d.12.temp.tr <- diff(d.temp.tr, lag=12)
var(d.12.temp.tr)
dd.12.temp.tr <- diff(d.12.temp.tr, lag=1)
var(dd.12.temp.tr)
# Variance rose, so no longer need to do any differencing, d.12.temp.tr is what I want
# SARIMA model with s=12, d=1, D=1

# Statistical tests for stationarity
Box.test(d.12.temp.tr) # stationary
adf.test(d.12.temp.tr) # stationary
```

#### Diagnostics
```{r}
acf(d.12.temp.tr, lag.max=30)
# significant autocorrelation at lags 1, 11, 12, and 13
pacf(d.12.temp.tr, lag.max=30)
# partial autocorrelation decays, then increases again at lag 11, switches signs at 12, then decays
```

